apiVersion: v2
name: ndb-operator-test
description: A Helm chart for Nutanix Database Kubernetes Operator
type: application
version: 0.5.11
appVersion: v0.5.1
maintainers:
  - name: Shivaprasad M B
    email: shivaprasad.mb@nutanix.com
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "Updated ndb-operator image to mrshivaprasad/ndb-operator-test:db-fix."
  artifacthub.io/license: Apache-2.0
  artifacthub.io/maintainers: |
    - name: Shivaprasad M B
      email: shivaprasad.mb@nutanix.com
  artifacthub.io/operator: "true"
  artifacthub.io/operatorCapabilities: Basic Install
  artifacthub.io/prerelease: "false"
  artifacthub.io/images: |
    - name: mrshivaprasad/ndb-operator-test
      image: mrshivaprasad/ndb-operator-test:db-fix
    - name: kube-rbac-proxy
      image: bitnami/kube-rbac-proxy@sha256:696e043fa27df8076bbe0581c924b79938509d26c0bd98cbde8d0b3c7def527c