replicaCount: 1

# kube-rbac-proxy image (Bitnami image with digest for CVE-hardened build)
kubeRbacProxy:
  image: bitnami/kube-rbac-proxy@sha256:696e043fa27df8076bbe0581c924b79938509d26c0bd98cbde8d0b3c7def527c

image:
  repository: mrshivaprasad/ndb-operator-test
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "ns-2"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

resources:
  kubeProxy:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 5m
      memory: 64Mi
  controller:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}